
#======================
#=== RAINFALL SETTINGS
#======================
type: conditional
conditions:
  - entity: input_boolean.irrigation_show_rainfall_settings
    state: "on"
card:
  type: custom:stack-in-card
  cards:

    - type: entities
      entities:
        - type: divider
      style: >
        ha-card {
          margin-top: -0.5em;
          margin-bottom: -1em;
        }

    #=== General Rainfall Settings
    - !include
        - ../../includes/titles.yaml
        - title: General Rainfall Settings
          font_size: 18px
          font_family: Oswald
          color: var(--secondary-text-color)
          margin_bottom: -1.5em
          margin_left: 0.5em

    - type: entities
      entities:
        #=== Number of days history
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_days_of_rainfall_history_used
              name: Number of days history to use
              secondary_info: (0 to 4) If zero only rainfall today is used
              round: 0

        #=== Rainfall threshold
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_threshold
              name: Rainfall threshold
              secondary_info: If this threshold is reached no watering takes place
              margin_top: -0.5em

        - type: divider

    #=== Percentage Of Rainfall To Include
    - !include
        - ../../includes/titles.yaml
        - title: Percentage Of Rainfall To Include
          font_size: 18px
          font_family: Oswald
          color: var(--secondary-text-color)
          margin_top: -1.25em
          margin_bottom: -1.5em
          margin_left: 0.5em

    - type: entities
      entities:
        #=== Yesterday
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_percentage_1
              name: Yesterday

        #=== Two days ago
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_percentage_2
              name: Two days ago
              margin_top: -0.5em

        #=== Three days ago
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_percentage_3
              name: Three days ago
              margin_top: -0.5em

        #=== Four days ago
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_percentage_4
              name: Four days ago
              margin_top: -0.5em

        - type: divider

    #=== Rainfall Data
    - !include
        - ../../includes/titles.yaml
        - title: Rainfall Data
          font_size: 18px
          font_family: Oswald
          color: var(--secondary-text-color)
          margin_top: -1.25em
          margin_bottom: -1.5em
          margin_left: 0.5em

    - type: entities
      entities:
        #=== Multiplier used in calculations
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_multiplier
              name: Multiplier used in calculations
              secondary_info: Calculated based on rainfall and threshold
              tap_action: none

        #=== The average of all Smartweather sensors
        - !include
            - item_settings_line.yaml
            - entity: sensor.smartweather_average_rain_today
              name: Rainfall today
              secondary_info: The average of all Smartweather sensors
              icon: mdi:weather-rainy
              tap_action: none
              margin_bottom: -1em

    #=== Stations Used
    - type: custom:mod-card
      style: |
        ha-card {
          margin: 0em 1em 0em 1em;
        }
      card:
        type: horizontal-stack
        cards:
          - type: custom:button-card
            name: STATIONS<br>USED
            styles:
              card:
                - font-size: 12px
                - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
                - background: none
                - margin: 0em 0em 0em 0em
                - color: var(--secondary-text-color)
            tap_action:
              action: call-service
              service: browser_mod.popup
              service_data:
                title: Smartweather Rainfall
                card:
                  type: markdown
                  content: >
                    {% set id1 = states('input_text.smartweather_location_code1') %}
                    {% set id2 = states('input_text.smartweather_location_code2') %}
                    {% set id3 = states('input_text.smartweather_location_code3') %}
                    {% set id4 = states('input_text.smartweather_location_code4') %}
                    {% set id5 = states('input_text.smartweather_location_code5') %}

                    {% set name1 = states('input_text.smartweather_location_name1') %}
                    {% set name2 = states('input_text.smartweather_location_name2') %}
                    {% set name3 = states('input_text.smartweather_location_name3') %}
                    {% set name4 = states('input_text.smartweather_location_name4') %}
                    {% set name5 = states('input_text.smartweather_location_name5') %}

                    {% set today1 = states('sensor.smartweather_1_rain_today') %}
                    {% set yesterday1 = states('sensor.smartweather_1_rain_yesterday') %}
                    {% set today2 = states('sensor.smartweather_2_rain_today') %}
                    {% set yesterday2 = states('sensor.smartweather_2_rain_yesterday') %}
                    {% set today3 = states('sensor.smartweather_3_rain_today') %}
                    {% set yesterday3 = states('sensor.smartweather_3_rain_yesterday') %}
                    {% set today4 = states('sensor.smartweather_4_rain_today') %}
                    {% set yesterday4 = states('sensor.smartweather_4_rain_yesterday') %}
                    {% set today5 = states('sensor.smartweather_5_rain_today') %}
                    {% set yesterday5 = states('sensor.smartweather_5_rain_yesterday') %}


                    Station | Today (mm) | Yesterday (mm)
                      ---|:---:|:---:
                    {{ id1 }}: {{ name1 }} | {{ today1 | round(1) }} | {{ yesterday1 | round(1) }}

                    {{ id2 }}: {{ name2 }} | {{ today2 | round(1) }} | {{ yesterday2 | round(1) }}

                    {{ id3 }}: {{ name3 }} | {{ today3 | round(1) }} | {{ yesterday3 | round(1) }}

                    {{ id4 }}: {{ name4 }} | {{ today4 | round(1) }} | {{ yesterday4 | round(1) }}

                    {{ id5 }}: {{ name5 }} | {{ today5 | round(1) }} | {{ yesterday5 | round(1) }}
                deviceID:
                  - this
                style:
                  font-family: Oswald
                  font-size: 14px
                  border-radius: 1em
                  box-shadow: 0em 0em 0.5em
                  opacity: 0.9

          - !include
            - ../../includes/button_boolean_check_box.yaml
            - entity: input_boolean.smartweather_rainfall_use_location_1
              name: !secret smartweather_location_code_1
              card_margin_top: 0.-1em
              name_justify_self: right
              size: 100%
              grid_template_columns: 1fr 25%

          - !include
            - ../../includes/button_boolean_check_box.yaml
            - entity: input_boolean.smartweather_rainfall_use_location_2
              name: !secret smartweather_location_code_2
              card_margin_top: 0.-1em
              name_justify_self: right
              size: 100%
              grid_template_columns: 1fr 25%

          - !include
            - ../../includes/button_boolean_check_box.yaml
            - entity: input_boolean.smartweather_rainfall_use_location_3
              name: !secret smartweather_location_code_3
              card_margin_top: 0.-1em
              name_justify_self: right
              size: 100%
              grid_template_columns: 1fr 25%

          - !include
            - ../../includes/button_boolean_check_box.yaml
            - entity: input_boolean.smartweather_rainfall_use_location_4
              name: !secret smartweather_location_code_4
              card_margin_top: 0.-1em
              name_justify_self: right
              size: 100%
              grid_template_columns: 1fr 25%

          - !include
            - ../../includes/button_boolean_check_box.yaml
            - entity: input_boolean.smartweather_rainfall_use_location_5
              name: !secret smartweather_location_code_5
              card_margin_top: 0.-1em
              name_justify_self: right
              size: 100%
              grid_template_columns: 1fr 25%

    - type: entities
      entities:
        #=== Rainfall yesterday
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_1
              name: Rainfall Yesterday
              tap_action: none
              margin_top: -1em

        #=== Rainfall two days ago
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_2
              name: Two days ago
              tap_action: none
              margin_top: -0.5em

        #=== Rainfall three days ago
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_3
              name: Three days ago
              tap_action: none
              margin_top: -0.5em

        #=== Rainfall four days ago
        - !include
            - item_settings_line.yaml
            - entity: input_number.irrigation_rainfall_4
              name: Four days ago
              tap_action: none
              margin_top: -0.5em

