# lovelace_gen

#==================================
#=== Use Forecast High Temperature
#==================================
type: horizontal-stack
cards:
  - type: custom:button-card
    color_type: blank-card

  - type: custom:button-card
    color_type: blank-card

  - type: custom:hui-element
    card_type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: input_select.irrigation_high_temp_options
        show_state: true
        show_name: false
        # name: Use forecast high temperature in adjustment calculations
        icon: mdi:square-edit-outline
        size: 60%
        styles:
          grid:
            - grid-template-areas: '"s i"'
            - grid-template-columns: '1fr 20%'
            - grid-template-rows: 1fr
          card:
            - padding: 0em 0em
            - margin-top: 0.2em
            - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
            - font-size: 14px
            - box-shadow: none
            - background: none
          state:
            - justify-self: right
            - align-self: centre
        tap_action:
          action: call-service
          service: browser_mod.popup
          service_data:
            title: "High Temperature Options"
            hide_header: true
            card:
              type: vertical-stack
              cards:
                - type: markdown
                  content: Choose which high temperature measurement is used.
                  style: >
                    ha-card {
                      font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
                      font-size: 16px;
                      text-align: center;
                    }
                - type: entities
                  entities:
                    - entity: input_select.irrigation_high_temp_options
                  style: >
                    ha-card {
                      font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
                    }
            deviceID:
              - this
            style:
              $: |
                .mdc-dialog {
                    backdrop-filter: blur(5px);
                  }
                .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
                    border-radius: 1em;
                    box-shadow: 0em 0em 0.5em;
                  }
            