
#=== Forecast vs. Actual High Temperature Graph
type: custom:mini-graph-card
entities:
  - entity: sensor.dark_sky_current_temperature
    color: SteelBlue
    show_legend: false
  - entity: sensor.dark_sky_forecast_daytime_high_temperature_0d
    color: IndianRed
    show_legend: false
  - entity: binary_sensor.above_horizon
    name: Night
    y_axis: secondary
    color: black
    show_line: false
    show_points: false
    show_legend: false
line_width: 2
hours_to_show: 48
points_per_hour: 4
aggregate_func: min
show:
  name: false
  state: false
  labels: true
  labels_secondary: false
  icon: false
state_map:
  - value: 'on'
    label: 'Day'
  - value: 'off'
    label: 'Night'
tap_action:
  action: none

