
#===============================================
#=== Forecast High vs. Actual Temperature Graph
#===============================================
type: custom:mini-graph-card
entities:
  #=== Forecast
  - entity: sensor.irrigation_sensor_forecast_high_temp
    color: IndianRed
    show_legend: false
  #=== Actual
  - entity: sensor.irrigation_sensor_current_temp
    color: SteelBlue
    show_legend: false
  - entity: binary_sensor.above_horizon
    name: Night
    y_axis: secondary
    color: black
    show_line: false
    show_points: false
    show_legend: false
lower_bound: 0
line_width: 2
hours_to_show: 48
points_per_hour: 4
aggregate_func: min
show:
  fill: fade
  name: false
  state: false
  labels: false
  points: false
  labels_secondary: false
  icon: false
state_map:
  - value: 'on'
    label: 'Day'
  - value: 'off'
    label: 'Night'
tap_action:
  action: none
style: >
  ha-card {
    box-shadow: none;
    background: none;
    border-radius: 0px;
  }

