
#====================
#=== EDIT USER NAMES
#====================
type: horizontal-stack
cards:
  - type: custom:button-card
    color_type: blank-card

  - type: custom:button-card
    color_type: blank-card

  - type: custom:button-card
    name: 'â€¢  Edit user names '
    icon: mdi:square-edit-outline
    size: 60%
    styles:
      grid:
        - grid-template-areas: '"n i"'
        - grid-template-columns: 1fr 20%
        - grid-template-rows: min-content
      card:
        - font-family: "[[[ return states['input_text.irrigation_ui_font_family'].state ]]]"
        - font-size: 12px
        - padding: 0em 0.2em 0em
        - margin-top: 0em
        - box-shadow: none
      name:
        - color: var(--secondary-text-color)
        - justify-self: right
    tap_action:
      action: call-service
      service: browser_mod.popup
      service_data:
        title: User names
        card:
          type: vertical-stack
          cards:
            - type: markdown
              content: >
                Choose the name of up to two users to receive notifications about
                irrigation events.
              style: >
                ha-card {
                  box-shadow: none;
                  padding: 0em 0em 0em 1em;
                  background: var(--paper-dialog-background-color);
                  margin: 0em;
                  font-size: 16px;
                }
            - type: entities
              entities:
                - entity: input_text.notifications_user1_name
                  name: User 1
                - entity: input_text.notifications_user2_name
                  name: User 2
              style: >
                ha-card {
                  box-shadow: none;
                  border-radius: 0em 0em 1em 1em;
                  background: var(--paper-dialog-background-color);
                }
            - type: markdown
              content: >
                These names are held in:
              style: >
                ha-card {
                  box-shadow: none;
                  padding: 0em 0em 0em 1em;
                  background: var(--paper-dialog-background-color);
                  font-size: 16px;
                }
            - type: markdown
              content: >
                input_text.notifications_user[1, 2]_name
              style: >
                ha-card {
                  box-shadow: none;
                  background: var(--paper-dialog-background-color);
                  text-align: center;
                  font-family: Roboto;
                  font-size: 16px;
                }
            - type: markdown
              content: >
                and can be used in your notification processing as approriate.


                When a notification is issued, 'script.notify' is called.


                This script is <b>not</b> inlcuded in this package,
                you will need to write your own.
              style: >
                ha-card {
                  box-shadow: none;
                  padding: 0em 0em 0em 1em;
                  background: var(--paper-dialog-background-color);
                  font-size: 16px;
                }
        deviceID:
          - this
        style:
          font-family: >
            [[[
              return states['input_text.irrigation_ui_font_family'].state
            ]]]
          box-shadow: 0em 0em 0.5em
          border-radius: 1em
          opacity: 0.9
