
#================
#=== HELP BUTTON
#================
type: custom:button-card
icon: mdi:information-outline
show_name: false
size: 100%
styles:
  card:
    - background: none
    # - height: 1.9em
    - width: 1.9em
    - box-shadow: none
  icon:
    - color: var(--accent-color)
tap_action:
  action: call-service
  service: browser_mod.popup
  service_data:
    title: "\U00002139 INFORMATION"
    card:
      type: markdown
      content: >
        Tap a Cycle Start Time to edit the schedule time

        Tap a Cycle header to edit the name


        Tap a Zone to edit its information


        Selecting 'Testing Mode' will change run times to seconds.

        e.g a run time of 5 minutes will run for 5 seconds.


        ---


        #### Adjusting Duration For Weather (Experimental)

        Turning on weather adjustments will adjust watering time based on temperature
        and/or rainfall.


        See RAINFALL & TEMPERATURE settings.
      # style: >
      #   ha-card {
      #     border-radius: 0em 0em 1em 1em
      #   }

    deviceID:
      - this
    # style:
    #   font-family: >
    #     [[[
    #       return states['input_text.irrigation_ui_font_family'].state
    #     ]]]
    #   font-size: 14px
    #   box-shadow: 0em 0em 0.5em
    #   border-radius: 1em
    #   overflow: hidden
    #   opacity: 0.9

    style:
      $: |
        .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
          border-radius: 1em;
          box-shadow: 0em 0em 0.5em;
        }
      .: |
        :host {
          --mdc-theme-surface: var(--paper-dialog-background-color);
          --ha-card-background: var(--paper-dialog-background-color);
          --secondary-background-color: var(--paper-dialog-background-color);
          opacity: 0.9;
        }
