
#==========================
#=== SMARTWEATHER STATIONS
#==========================
type: conditional
conditions:
  - entity: input_boolean.irrigation_show_smartweather_stations
    state: 'on'
card:
  type: custom:hui-element
  card_type: horizontal-stack
  cards:
    #================================
    #=== SMARTWEATHER STATIONS TITLE
    #================================
    - type: custom:button-card
      name: SMARTWEATHER<br>STATIONS
      styles:
        card:
          - font-size: 11px
          - font-family: >
              [[[
                return states['input_text.irrigation_ui_font_family'].state
              ]]]
          - background: none
          - box-shadow: none
          - color: var(--secondary-text-color)
          - margin-top: 0.5em
      tap_action:
        action: call-service
        service: browser_mod.popup
        service_data:
          title: Smartweather Rainfall
          hide_header: true
          card:
            type: markdown
            content: >
              {% set id1 = states('input_text.smartweather_location_code1') %}
              {% set id2 = states('input_text.smartweather_location_code2') %}
              {% set id3 = states('input_text.smartweather_location_code3') %}
              {% set id4 = states('input_text.smartweather_location_code4') %}
              {% set id5 = states('input_text.smartweather_location_code5') %}

              {% set name1 = state_attr('sensor.smartweather_1', 'station_name') %}
              {% set name2 = state_attr('sensor.smartweather_2', 'station_name') %}
              {% set name3 = state_attr('sensor.smartweather_3', 'station_name') %}
              {% set name4 = state_attr('sensor.smartweather_4', 'station_name') %}
              {% set name5 = state_attr('sensor.smartweather_5', 'station_name') %}

              {% set today1 = states('sensor.smartweather_1_rain_today') %}
              {% set yesterday1 = states('sensor.smartweather_1_rain_yesterday') %}
              {% set today2 = states('sensor.smartweather_2_rain_today') %}
              {% set yesterday2 = states('sensor.smartweather_2_rain_yesterday') %}
              {% set today3 = states('sensor.smartweather_3_rain_today') %}
              {% set yesterday3 = states('sensor.smartweather_3_rain_yesterday') %}
              {% set today4 = states('sensor.smartweather_4_rain_today') %}
              {% set yesterday4 = states('sensor.smartweather_4_rain_yesterday') %}
              {% set today5 = states('sensor.smartweather_5_rain_today') %}
              {% set yesterday5 = states('sensor.smartweather_5_rain_yesterday') %}


              Station | Today (mm) | Yesterday (mm)
                ---|:---:|:---:
              {{ id1 }}: {{ name1 }} | {{ today1 | round(1) }} | {{ yesterday1 | round(1) }}

              {{ id2 }}: {{ name2 }} | {{ today2 | round(1) }} | {{ yesterday2 | round(1) }}

              {{ id3 }}: {{ name3 }} | {{ today3 | round(1) }} | {{ yesterday3 | round(1) }}

              {{ id4 }}: {{ name4 }} | {{ today4 | round(1) }} | {{ yesterday4 | round(1) }}

              {{ id5 }}: {{ name5 }} | {{ today5 | round(1) }} | {{ yesterday5 | round(1) }}
            style: >
              ha-card {
                font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
              }
          deviceID:
            - this
          style:
            $: |
              .mdc-dialog {
                  backdrop-filter: blur(5px);
                }
              .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
                  border-radius: 1em;
                  box-shadow: 0em 0em 0.5em;
                }
          
    #========================
    #=== STATIONS TO INCLUDE
    #========================
    - !include
      - item_settings_smartweather_check_box.yaml
      - entity: input_boolean.smartweather_rainfall_use_location_1

    - !include
      - item_settings_smartweather_check_box.yaml
      - entity: input_boolean.smartweather_rainfall_use_location_2

    - !include
      - item_settings_smartweather_check_box.yaml
      - entity: input_boolean.smartweather_rainfall_use_location_3

    - !include
      - item_settings_smartweather_check_box.yaml
      - entity: input_boolean.smartweather_rainfall_use_location_4

    - !include
      - item_settings_smartweather_check_box.yaml
      - entity: input_boolean.smartweather_rainfall_use_location_5

