
#======================
#=== RAINFALL SETTINGS
#======================
type: entities
entities:

  - type: custom:hui-element
    card_type: vertical-stack
    cards:

      #=== General Rainfall Settings
      - type: custom:button-card  
        show_icon: false
        name: GENERAL RAINFALL SETTINGS
        tap_action:
          action: none
        styles: &title_style
          card:
            - color: var(--secondary-text-color)
            - box-shadow: none
            - border-radius: 0em
            - background: none
            - padding-top: 0em
            - padding-bottom: 0em
            - padding-left: 0.5em
            - font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
            - font-size: 18px
          name:
            - justify-self: start
            - border-left: 3px solid var(--accent-color)
            - padding-left: 0.5em

      #=== Number of days history
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_days_of_rainfall_history_used
            name: Number of days history to use
            label: (0 to 4) If zero only rainfall today is used
            round: 0

      #=== Rainfall threshold
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_threshold
            name: Rainfall threshold
            label: If this threshold is reached no watering takes place

      #=== Ignore schedules if raining
      - !include
          - ../item_settings_line.yaml
          - entity: input_boolean.irrigation_ignore_schedule_if_raining
            name: Ignore schedules if it is raining
            padding: 0em 0em 0.3em 0em

      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Percentage Of Rainfall To Include
      - type: custom:hui-element
        card_type: horizontal-stack
        cards:

          - type: custom:button-card  
            show_icon: false
            name: RAINFALL INCLUDED IN CALCULATIONS
            tap_action:
              action: none
            styles: *title_style

          - type: custom:button-card
            icon: mdi:square-edit-outline
            styles:
              card:
                - box-shadow: none
                - width: 4em
                - padding-right: 0.5em
            tap_action:
              action: fire-dom-event
              browser_mod:
                command: popup
                title: Rainfall Included in Calculations
                card:
                  type: entities
                  entities:
                    - entity: input_number.irrigation_rainfall_percentage_1
                    - entity: input_number.irrigation_rainfall_percentage_2
                    - entity: input_number.irrigation_rainfall_percentage_3
                    - entity: input_number.irrigation_rainfall_percentage_4
                  style: >
                    ha-card {
                      box-shadow: none;
                      border-radius: 0em 0em 1em 1em;
                      background: var(--paper-dialog-background-color);
                    }
                style:
                  font-family: >
                    [[[
                      return states['input_text.irrigation_ui_font_family'].state
                    ]]]
                  box-shadow: 0em 0em 0.5em
                  border-radius: 1em
                  overflow: hidden
                  opacity: 0.9


      #=== Yesterday
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_1
            name: Yesterday
            tap_action: none
            padding: 0.3em 0em 0em 0em

      #=== Two days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_2
            name: Two days ago
            tap_action: none

      #=== Three days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_3
            name: Three days ago
            tap_action: none

      #=== Four days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_percentage_4
            tap_action: none
            name: Four days ago
            padding: 0em 0em 0.3em 0em


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Rainfall Data
      - type: custom:button-card  
        show_icon: false
        name: RAINFALL DATA
        tap_action:
          action: none
        styles: *title_style

      #=== Multiplier used in calculations
      - !include
          - ../item_settings_multiplier_line.yaml
          - entity: input_number.irrigation_rainfall_multiplier
            name: "Current Multiplier ( \U00002139 )"
            label: Calculated based on rainfall and threshold
            padding: 0.3em 0em 0em 0em

      #=== Rainfall today
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_today
            name: Rainfall Today
            icon: mdi:weather-rainy
            round: 1
            tap_action: none

      #=== Rainfall yesterday
      - !include
          - ../item_settings_line.yaml
          - entity: sensor.irrigation_sensor_rainfall_yesterday
            name: Rainfall Yesterday
            icon: mdi:weather-rainy
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 1 ? 'none' : 'unset' ]]]"

      #=== Rainfall two days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_2
            name: Two days ago
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 2 ? 'none' : 'unset' ]]]"

      #=== Rainfall three days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_3
            name: Three days ago
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 3 ? 'none' : 'unset' ]]]"

      #=== Rainfall four days ago
      - !include
          - ../item_settings_line.yaml
          - entity: input_number.irrigation_rainfall_4
            name: Four days ago
            round: 1
            tap_action: none
            display_condition: "[[[ return states['input_number.irrigation_days_of_rainfall_history_used'].state < 4 ? 'none' : 'unset' ]]]"
            padding: 0em 0em 0.3em 0em

      #=== SmartWeather Stations Used
      - !include item_settings_smartweather_stations_used.yaml


      #-------------------------
      - type: custom:hui-element
        row_type: divider
      #-------------------------


      #=== Forecast Rain vs. Actual Rain
      - type: custom:button-card  
        show_icon: false
        name:  RAINFALL - <font color=IndianRed>Forecast</font> vs. <font color=SteelBlue>Actual</font>
        tap_action:
          action: none
        styles: *title_style

      #=== Forecast vs. Actual Rian Graph
      - !include item_settings_rainfall_graph.yaml

style: >
  ha-card {
    box-shadow: none;
    margin-top: -0.75em;
  }
