# lovelace_gen

#=====================================
#=== USE FORECAST HIGH TEMPERATURE
#===
#=== Option to use Forecast or Actual
#=== Temperatures in calculations
#=====================================
type: horizontal-stack
cards:
  - type: custom:button-card
    color_type: blank-card

  - type: custom:button-card
    color_type: blank-card

  - type: custom:hui-element
    card_type: horizontal-stack
    cards:
      - type: custom:button-card
        entity: input_select.irrigation_high_temp_options
        show_state: true
        show_name: false
        icon: mdi:square-edit-outline
        size: 60%
        styles:
          grid:
            - grid-template-areas: '"s i"'
            - grid-template-columns: '1fr 20%'
            - grid-template-rows: 1fr
          card:
            - padding: 0em 0em
            - margin-top: 0.2em
            - font-family: >
                [[[
                  return states['input_text.irrigation_ui_font_family'].state
                ]]]
            - font-size: 14px
            - background: none
          state:
            - justify-self: right
            - align-self: centre

        #=== SHOW CHOICE OPTIONS
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: "High Temperature Options"
              content:
                type: vertical-stack
                cards:
                  - type: markdown
                    content: Choose which high temperature measurement is used.
                    card_mod:
                      style: >
                        ha-card {
                          font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
                          font-size: 16px;
                          text-align: center;
                        }
                  - type: entities
                    entities:
                      - entity: input_select.irrigation_high_temp_options
                    card_mod:
                      style: >
                        ha-card {
                          font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
                        }
              #=== Style needed for pop-up title
              style:
                $: |
                  .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
                      font-family: {% raw %}{{ states('input_text.irrigation_ui_font_family') }}{% endraw %};
                    }
            